### ISSUE TITLE
Audio recorder creating corrupt wav files

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-sys#155]
The current Zynthian audio recorder creates wav files with invalid headers. This upsets some players.

**To Reproduce**
1. Admin Menu
2. Start recording
3. Stop recording
4. Use sox or similar to inspect resulting wav file

**Expected behaviour**
WAV file created with correct RIFF header

**Actual behaviour**
WAV file created with incorrect RIFF header

**Comment by jofemodo** [comment]
Solved by https://github.com/zynthian/zynthian-sys/commit/58fa552bdd6ea5a39d4abff4726c7666df4f5201.
Now "16 bit integer" format is used instead of "32 bit float". This works OK on firefox and other browsers. Regarding Sox, it seems to be too strict, but generated wav files works everywhere now.
See: https://github.com/kmatheussen/jack_capture/issues/37
